---
title: "Crimes - EDA"
author: "Sam Lee"
format: pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
library(lubridate)
library(animation)

crimes <- read_csv("raw_data/Crimes.csv")
moons <- read_csv("raw_data/full_moon.csv") %>%
  mutate(Day = dmy(FullMoonDates))
holidays <- read_csv("raw_data/holidays.csv") %>%
  mutate(Day = ymd(Date))
weather <- read_csv("raw_data/weather.csv") %>%
  mutate(Day = ymd(datetime))
#weather.covariates = colnames(weather) %>% 
#  setdiff(c("name", "datetime", "stations", "Day"))
#maps.api.key = read_file("maps_api.txt")

crimes$Date <- mdy_hms(crimes$Date)
crimes$Day <- as.Date(crimes$Date)
crimes$Day <- as.Date(crimes$Date)

cutoff.date = max(
  c(min(crimes$Day), min(holidays$Day), min(weather$Day), min(moons$Day))
)

crimes.cleaned <- crimes %>% 
  left_join(weather) %>%
  left_join(holidays) %>%
  left_join(moons) %>%
  mutate(
    Holiday = ifelse(is.na(Holiday), "", Holiday),
    `Day of Week` = wday(Day),
    FullMoon = ifelse(is.na(FullMoonDates),0,1)
  ) %>% filter(
    Day >= cutoff.date
  )
  
factors = c("Date", "Primary Type", "Location Description", "Arrest",
            "Domestic", "Community Area", "Year", "Latitude", "Longitude",
            "Day", weather.covariates, "FullMoon")

crimes.cleaned <- crimes.cleaned[,factors]
write_csv(crimes.cleaned, "crimes_cleaned.csv")
```

```{r fig.width=8, fig.height=8, message=F, warning=F}
#In the FBI's Uniform Crime Reporting (UCR) Program, violent crime is composed 
#of four offenses: murder and nonnegligent manslaughter, forcible rape, 
#robbery, and aggravated assault.

allcrimes = sort(crimes$`Primary Type`) %>% unique()
violence.key <- c(0,1,1,1,0,1,0,1,0,0,0,1,1,0,1,1,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,1,0,0,0,0)
mapping <- setNames(seq_along(unique(allcrimes)), unique(allcrimes))
crimes$Violent <- violence.key[unname(mapping[crimes$`Primary Type`])]

register_google(key=maps.api.key)
chicago_map <- get_map(location = c(lon=-87.72, lat = 41.881832),
                       zoom = 13)

ggmap(chicago_map) +
  geom_point(data = filter(crimes, Year==2023),
             aes(x = Longitude, y = Latitude, color=as.factor(Violent)),
             alpha=0.2) +
  labs(title = "Crimes in District 11 During 2023")


marginal_crimes <- function(df, year=2023){
  df %>% filter(Year %in% year) %>%
    group_by(Day) %>% summarize(
    n_crimes = n(),
    violent_crimes = sum(Violent)
  ) %>%
    ggplot()+
    geom_line(aes(x=Day, y=n_crimes))+
    geom_line(aes(x=Day, y=violent_crimes), color="red")+
    labs(
      x="Date",
      y="# of Crimes"
    )+
    theme_minimal()
}
marginal_crimes(crimes, year=2022:2024)

write_csv(crimes.cleaned, "crimes_cleaned.csv")
```